language: node_js
node_js:
  - "node"
  - "iojs"
  - "iojs-v1"
  - "iojs-v2"
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
after_script:
  - npm run coveralls